# https://quay.io/repository/centos/centos?tab=tags&tag=stream9
# FROM centos:centos9
fROM quay.io/centos/centos9:latest

LABEL org.opencontainers.image.authors="githubfoam"

RUN set -xe && \
    yum update -qy && \
    yum install zmap

ENTRYPOINT ["zmap"]
CMD ["-h"]

