FROM kalilinux/kali-rolling
LABEL org.opencontainers.image.authors="githubfoam"


#clean start
RUN set -xe && \
    apt-get update -y && apt-get upgrade -y && \
    apt-get autoremove - && apt-get clean && \
    apt-get install -y --no-install-recommends \
    zmap

ENTRYPOINT ["zmap"]
CMD ["-h"]

