# https://quay.io/repository/centos/centos
FROM quay.io/centos/centos:stream9

LABEL org.opencontainers.image.authors="githubfoam"

RUN set -xe && \
    yum update -qy && \
    yum install zmap

ENTRYPOINT ["zmap"]
CMD ["-h"]

