name: "zmap with centos8 CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-centos8-latest-job:
    name: "zmap with centos8 on ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "centos" #https://hub.docker.com/_/centos
      version: "latest"
      name: "centos8/zmap"
      dockerfiledir: "dockerfiles"
      dockerfilename: "Dockerfile.centos8.zmap"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release  
    - name: "build zmap with centos8 "
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version}
        echo "################## ENTRYPOINT ##################" 
        docker inspect -f '{{.Config.Entrypoint}}' ${name}:${version}
        docker run ${name}:${version} zmap -h       
        # docker run ${name}:${version} zmap -p 80 172.217.0.0/24 -o IPresults.csv # not OK


