name: "zmap with fedora CI workflow"


on:
  push:
    branches:
      - 'test'
    tags:
      - 'v*'    
  pull_request:
    branches:
      - 'test'

jobs:

  zmap-fedora-ubuntu-latest-job:
    name: "zmap with fedora on ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "fedora/zmap"
      dockerfiledir: "dockerfiles"      
      dockerfilename: "Dockerfile.fedora.zmap"
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v3
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        # cat /etc/os-release

    - name: "build zmap with fedora"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version}     
        echo "################## ENTRYPOINT ##################" 
        docker inspect -f '{{.Config.Entrypoint}}' ${name}:${version}
        docker run ${name}:${version} zmap -h 
        # List available probe modules
        # IPv6 support
        docker run --rm --net=host ${name}:${version} zmap --list-probe-modules                                         
        # docker run --rm --net=host ${name}:${version} zmap --probe-module=icmp6_echoscan                 
        # docker run ${name}:${version} zmap -p 80 172.217.0.0/24 -o IPresults.csv # not OK

    # https://github.com/docker/login-action
    - name: "Login to DockerHub"
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

    # https://github.com/docker/login-action
    - name: "Login to Github Packages"
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}    

      # https://github.com/docker/metadata-action
    - name: "Extract metadata (tags, labels) for Docker"
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
            # my-docker-hub-namespace/my-docker-hub-repository
            ${{ secrets.DOCKERHUB_USERNAME }}/zmap-fedora
            ghcr.io/${{ github.repository }}

    # https://github.com/docker/build-push-action
    - name: "Build and push Docker images"
      uses: docker/build-push-action@v3
      with:
          context: .
          path: ./dockerfiles/Dockerfile.fedora.zmap
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}}          