name: "zmap with fedora CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  zmap-fedora-ubuntu-latest-job:
    name: "zmap with fedora on ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "archlinux" #https://hub.docker.com/_/archlinux
      version: "latest"
      name: "fedora/zmap"
      dockerfiledir: "dockerfiles"      
      dockerfilename: "Dockerfile.fedora.zmap"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
    - name: "build zmap with fedora"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        sudo docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version}
        docker system df -v               
        docker image inspect ${name}:${version}     
        echo "################## ENTRYPOINT ##################" 
        docker inspect -f '{{.Config.Entrypoint}}' ${name}:${version}
        docker run ${name}:${version} zmap -h 
        # List available probe modules
        # IPv6 support
        docker run --rm --net=host ${name}:${version} zmap --list-probe-modules                                         
        # docker run --rm --net=host ${name}:${version} zmap --probe-module=icmp6_echoscan                 
        # docker run ${name}:${version} zmap -p 80 172.217.0.0/24 -o IPresults.csv # not OK
    - name: "publish zmap with fedora"
      run: |
        docker image ls