name: "zmap with kalilinux/kali-rolling  CI workflow"

on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:

  zmap-ubuntu-latest-job:
    name: "build zmap with kalilinux/kali-rolling on ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
      version: "latest"
      name: "kali/zmap"
      dockerfiledir: "dockerfiles"
      dockerfilename: "Dockerfile.zmap"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "build zmap with kalilinux/kali-rolling "
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not usedi
        whoami
        echo ${USER} 
        #Add current logged in user to the docker group.
        sudo usermod -aG docker ${USER}
        id  ${USER}
        docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version} 
        docker system df -v               
        docker image inspect ${name}:${version} 
        echo "################## ENTRYPOINT ##################" 
        docker inspect -f '{{.Config.Entrypoint}}' ${name}:${version}
        docker run ${name}:${version} zmap -h    
        # List available probe modules
        # IPv6 support
        docker run --rm --net=host ${name}:${version} zmap --list-probe-modules                                         
        # docker run --rm --net=host ${name}:${version} zmap --probe-module=icmp6_echoscan                            
        # docker run ${name}:${version} zmap -p 80 172.217.0.0/24 -o IPresults.csv # not OK


           