name: "kali-tools-top10 with zmap CI workflow"


on:
  push:
    branches: [ main ]


jobs:

  zmap-ubuntu-latest-job:
    name: "build kali-tools-top10 with zmap on ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
      version: "latest"
      name: "kali/kali-tools-top10"
      dockerfiledir: "dockerfiles"
      dockerfilename: "Dockerfile.kalilinux.kali-tools-top10"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "build kali-tools-top10 with zmap"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used        whoami
        echo ${USER} 
        #Add current logged in user to the docker group.
        sudo usermod -aG docker ${USER}
        id  ${USER}
        docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename} 
        docker image ls
        docker image history ${name}:${version} 
        docker system df -v               
        docker image inspect ${name}:${version}    
        docker container ls -a
        docker run ${name}:${version} zmap -h
        # docker run --name toolkali ${name}:${version}  sh -c "hping3 --traceroute -v -1 www.wisetut.com"
    - name: "docker forensics"
      run: |
        # destroyed afterwards (use --rm )
        # all subsequent Dockerfile commands generate new images and the cache is not used
        docker build --no-cache --rm  -t ${name}:${version} . --file ${dockerfiledir}/${dockerfilename}
        docker image ls
        docker image history ${name}:${version} 
        docker system df -v               
        docker image inspect ${name}:${version}   
        docker container ls -a
        docker run --detach --name toolkali ${name}:${version}  
        docker container ls -a

        